// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/naming/v1/naming_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	NamingService_GetVerificationInfo_FullMethodName = "/agntcy.dir.naming.v1.NamingService/GetVerificationInfo"
	NamingService_Resolve_FullMethodName             = "/agntcy.dir.naming.v1.NamingService/Resolve"
)

// NamingServiceClient is the client API for NamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NamingService provides methods for name resolution and verification.
// Note: Verification is performed automatically by the backend scheduler
// for signed records with verifiable names (https://, http://, ans:// prefixes).
type NamingServiceClient interface {
	// GetVerificationInfo retrieves the verification info for a record.
	GetVerificationInfo(ctx context.Context, in *GetVerificationInfoRequest, opts ...grpc.CallOption) (*GetVerificationInfoResponse, error)
	// Resolve resolves a record reference (name with optional version) to CIDs.
	// Supports Docker-style references:
	//   - "name" -> returns all versions (newest first)
	//   - "name:version" -> returns the specific version
	//   - "name@cid" -> hash-verified lookup (latest version)
	//   - "name:version@cid" -> hash-verified lookup (specific version)
	//
	// Returns an error if no matching record is found.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type namingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamingServiceClient(cc grpc.ClientConnInterface) NamingServiceClient {
	return &namingServiceClient{cc}
}

func (c *namingServiceClient) GetVerificationInfo(ctx context.Context, in *GetVerificationInfoRequest, opts ...grpc.CallOption) (*GetVerificationInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerificationInfoResponse)
	err := c.cc.Invoke(ctx, NamingService_GetVerificationInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namingServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, NamingService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamingServiceServer is the server API for NamingService service.
// All implementations should embed UnimplementedNamingServiceServer
// for forward compatibility.
//
// NamingService provides methods for name resolution and verification.
// Note: Verification is performed automatically by the backend scheduler
// for signed records with verifiable names (https://, http://, ans:// prefixes).
type NamingServiceServer interface {
	// GetVerificationInfo retrieves the verification info for a record.
	GetVerificationInfo(context.Context, *GetVerificationInfoRequest) (*GetVerificationInfoResponse, error)
	// Resolve resolves a record reference (name with optional version) to CIDs.
	// Supports Docker-style references:
	//   - "name" -> returns all versions (newest first)
	//   - "name:version" -> returns the specific version
	//   - "name@cid" -> hash-verified lookup (latest version)
	//   - "name:version@cid" -> hash-verified lookup (specific version)
	//
	// Returns an error if no matching record is found.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
}

// UnimplementedNamingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNamingServiceServer struct{}

func (UnimplementedNamingServiceServer) GetVerificationInfo(context.Context, *GetVerificationInfoRequest) (*GetVerificationInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerificationInfo not implemented")
}
func (UnimplementedNamingServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedNamingServiceServer) testEmbeddedByValue() {}

// UnsafeNamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamingServiceServer will
// result in compilation errors.
type UnsafeNamingServiceServer interface {
	mustEmbedUnimplementedNamingServiceServer()
}

func RegisterNamingServiceServer(s grpc.ServiceRegistrar, srv NamingServiceServer) {
	// If the following call pancis, it indicates UnimplementedNamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NamingService_ServiceDesc, srv)
}

func _NamingService_GetVerificationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServiceServer).GetVerificationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamingService_GetVerificationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServiceServer).GetVerificationInfo(ctx, req.(*GetVerificationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamingService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamingServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamingService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamingServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NamingService_ServiceDesc is the grpc.ServiceDesc for NamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.naming.v1.NamingService",
	HandlerType: (*NamingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerificationInfo",
			Handler:    _NamingService_GetVerificationInfo_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _NamingService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agntcy/dir/naming/v1/naming_service.proto",
}
