// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: agntcy/dir/sign/v1/sign_service.proto

package v1

import (
	v1 "github.com/agntcy/dir/api/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options for OIDC-based signing.
type SignOptionsOIDC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fulcio authority access URL.
	// Default: https://fulcio.sigstore.dev
	FulcioUrl string `protobuf:"bytes,1,opt,name=fulcio_url,json=fulcioUrl,proto3" json:"fulcio_url,omitempty"`
	// Rekor transparency log access URL.
	// Default: https://rekor.sigstore.dev
	RekorUrl string `protobuf:"bytes,2,opt,name=rekor_url,json=rekorUrl,proto3" json:"rekor_url,omitempty"`
	// Timestamp authority access URL.
	// Default: https://timestamp.sigstore.dev/api/v1/timestamp
	TimestampUrl string `protobuf:"bytes,3,opt,name=timestamp_url,json=timestampUrl,proto3" json:"timestamp_url,omitempty"`
	// OIDC provider access URL.
	// Default: https://oauth2.sigstore.dev/auth
	OidcProviderUrl string `protobuf:"bytes,4,opt,name=oidc_provider_url,json=oidcProviderUrl,proto3" json:"oidc_provider_url,omitempty"`
	// OIDC client ID.
	// Default: sigstore
	OidcClientId string `protobuf:"bytes,5,opt,name=oidc_client_id,json=oidcClientId,proto3" json:"oidc_client_id,omitempty"`
	// OIDC client secret.
	// Required for confidential OIDC clients that require client authentication.
	// Default: empty
	OidcClientSecret string `protobuf:"bytes,6,opt,name=oidc_client_secret,json=oidcClientSecret,proto3" json:"oidc_client_secret,omitempty"`
	// Skip uploading signature to transparency log (Rekor).
	// Set to true for private signing where transparency log upload is not desired.
	// Note: Signatures created with this option cannot be verified against Rekor.
	// Default: false
	SkipTlog      bool `protobuf:"varint,7,opt,name=skip_tlog,json=skipTlog,proto3" json:"skip_tlog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOptionsOIDC) Reset() {
	*x = SignOptionsOIDC{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOptionsOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOptionsOIDC) ProtoMessage() {}

func (x *SignOptionsOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOptionsOIDC.ProtoReflect.Descriptor instead.
func (*SignOptionsOIDC) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{0}
}

func (x *SignOptionsOIDC) GetFulcioUrl() string {
	if x != nil {
		return x.FulcioUrl
	}
	return ""
}

func (x *SignOptionsOIDC) GetRekorUrl() string {
	if x != nil {
		return x.RekorUrl
	}
	return ""
}

func (x *SignOptionsOIDC) GetTimestampUrl() string {
	if x != nil {
		return x.TimestampUrl
	}
	return ""
}

func (x *SignOptionsOIDC) GetOidcProviderUrl() string {
	if x != nil {
		return x.OidcProviderUrl
	}
	return ""
}

func (x *SignOptionsOIDC) GetOidcClientId() string {
	if x != nil {
		return x.OidcClientId
	}
	return ""
}

func (x *SignOptionsOIDC) GetOidcClientSecret() string {
	if x != nil {
		return x.OidcClientSecret
	}
	return ""
}

func (x *SignOptionsOIDC) GetSkipTlog() bool {
	if x != nil {
		return x.SkipTlog
	}
	return false
}

// Options for OIDC-based verification.
type VerifyOptionsOIDC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TUF repository mirror URL.
	// Used to fetch trusted root material (certificates, keys) for verification.
	// Default: https://tuf-repo-cdn.sigstore.dev (public good instance)
	TufMirrorUrl string `protobuf:"bytes,1,opt,name=tuf_mirror_url,json=tufMirrorUrl,proto3" json:"tuf_mirror_url,omitempty"`
	// Path to a Sigstore TrustedRoot JSON file.
	// When provided, verification uses this file instead of fetching from TUF.
	// Required for fully offline/air-gapped verification.
	// The file contains Fulcio CAs, Rekor keys, TSA certs, and CT log keys.
	// Default: empty (uses TUF to fetch trusted root)
	TrustedRootPath string `protobuf:"bytes,2,opt,name=trusted_root_path,json=trustedRootPath,proto3" json:"trusted_root_path,omitempty"`
	// Skip transparency log (Rekor) verification.
	// Set to true for private infrastructure without Rekor,
	// or when signatures weren't uploaded to the transparency log.
	// Default: false
	IgnoreTlog bool `protobuf:"varint,3,opt,name=ignore_tlog,json=ignoreTlog,proto3" json:"ignore_tlog,omitempty"`
	// Skip timestamp authority (TSA) verification.
	// Set to true when timestamps aren't required or TSA wasn't used during signing.
	// Default: false
	IgnoreTsa bool `protobuf:"varint,4,opt,name=ignore_tsa,json=ignoreTsa,proto3" json:"ignore_tsa,omitempty"`
	// Skip Signed Certificate Timestamp (SCT) verification.
	// Set to true for private PKI where Certificate Transparency logs aren't used.
	// Default: false
	IgnoreSct     bool `protobuf:"varint,5,opt,name=ignore_sct,json=ignoreSct,proto3" json:"ignore_sct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOptionsOIDC) Reset() {
	*x = VerifyOptionsOIDC{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOptionsOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOptionsOIDC) ProtoMessage() {}

func (x *VerifyOptionsOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOptionsOIDC.ProtoReflect.Descriptor instead.
func (*VerifyOptionsOIDC) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyOptionsOIDC) GetTufMirrorUrl() string {
	if x != nil {
		return x.TufMirrorUrl
	}
	return ""
}

func (x *VerifyOptionsOIDC) GetTrustedRootPath() string {
	if x != nil {
		return x.TrustedRootPath
	}
	return ""
}

func (x *VerifyOptionsOIDC) GetIgnoreTlog() bool {
	if x != nil {
		return x.IgnoreTlog
	}
	return false
}

func (x *VerifyOptionsOIDC) GetIgnoreTsa() bool {
	if x != nil {
		return x.IgnoreTsa
	}
	return false
}

func (x *VerifyOptionsOIDC) GetIgnoreSct() bool {
	if x != nil {
		return x.IgnoreSct
	}
	return false
}

type SignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record reference to be signed
	RecordRef *v1.RecordRef `protobuf:"bytes,1,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	// Signing provider to use
	Provider      *SignRequestProvider `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{2}
}

func (x *SignRequest) GetRecordRef() *v1.RecordRef {
	if x != nil {
		return x.RecordRef
	}
	return nil
}

func (x *SignRequest) GetProvider() *SignRequestProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type SignRequestProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*SignRequestProvider_Key
	//	*SignRequestProvider_Oidc
	Request       isSignRequestProvider_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequestProvider) Reset() {
	*x = SignRequestProvider{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequestProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequestProvider) ProtoMessage() {}

func (x *SignRequestProvider) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequestProvider.ProtoReflect.Descriptor instead.
func (*SignRequestProvider) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{3}
}

func (x *SignRequestProvider) GetRequest() isSignRequestProvider_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SignRequestProvider) GetKey() *SignWithKey {
	if x != nil {
		if x, ok := x.Request.(*SignRequestProvider_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *SignRequestProvider) GetOidc() *SignWithOIDC {
	if x != nil {
		if x, ok := x.Request.(*SignRequestProvider_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

type isSignRequestProvider_Request interface {
	isSignRequestProvider_Request()
}

type SignRequestProvider_Key struct {
	// Sign with PEM-encoded public key
	Key *SignWithKey `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

type SignRequestProvider_Oidc struct {
	// Sign with OIDC provider
	Oidc *SignWithOIDC `protobuf:"bytes,2,opt,name=oidc,proto3,oneof"`
}

func (*SignRequestProvider_Key) isSignRequestProvider_Request() {}

func (*SignRequestProvider_Oidc) isSignRequestProvider_Request() {}

type SignWithKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Private key for signing.
	// Accepts either:
	// - PEM-encoded private key content (inline)
	// - Reference to a private key:
	//   - File path: "/path/to/cosign.key" or "./cosign.key"
	//   - HTTP(S) URL: "https://example.com/cosign.key"
	//   - Environment variable: "env://COSIGN_PRIVATE_KEY"
	//   - AWS KMS: "awskms://[ENDPOINT]/[ID/ALIAS/ARN]"
	//   - GCP KMS: "gcpkms://projects/[PROJECT]/locations/[LOC]/keyRings/[RING]/cryptoKeys/[KEY]"
	//   - Azure Key Vault: "azurekms://[VAULT_NAME][VAULT_URI]/[KEY]"
	//   - Hashicorp Vault: "hashivault://[KEY]"
	//   - Kubernetes secret: "k8s://[NAMESPACE]/[SECRET_NAME]"
	//   - PKCS11 token: "pkcs11:token=...;slot-id=...;object=..."
	//   - GitLab: "gitlab://[PROJECT]"
	PrivateKey string `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Password to unlock the private key (if encrypted).
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// X.509 certificate(s) for the signing key, PEM-encoded inline.
	// Unlike private_key, this field accepts no file, URL, or KMS references.
	// A single certificate or a chain may be given; the certificate whose
	// public key matches private_key is attached to Signature.certificate as
	// base64-encoded DER and the others are ignored. Signing fails when no
	// certificate matches. Not used with OIDC signing.
	Certificate   *string `protobuf:"bytes,3,opt,name=certificate,proto3,oneof" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignWithKey) Reset() {
	*x = SignWithKey{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignWithKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignWithKey) ProtoMessage() {}

func (x *SignWithKey) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignWithKey.ProtoReflect.Descriptor instead.
func (*SignWithKey) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{4}
}

func (x *SignWithKey) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SignWithKey) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *SignWithKey) GetCertificate() string {
	if x != nil && x.Certificate != nil {
		return *x.Certificate
	}
	return ""
}

type SignWithOIDC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for OIDC provider
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	// Signing options for OIDC
	Options       *SignOptionsOIDC `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignWithOIDC) Reset() {
	*x = SignWithOIDC{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignWithOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignWithOIDC) ProtoMessage() {}

func (x *SignWithOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignWithOIDC.ProtoReflect.Descriptor instead.
func (*SignWithOIDC) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{5}
}

func (x *SignWithOIDC) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *SignWithOIDC) GetOptions() *SignOptionsOIDC {
	if x != nil {
		return x.Options
	}
	return nil
}

type SignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cryptographic signature of the record
	Signature     *Signature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{6}
}

func (x *SignResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record reference to be verified
	RecordRef *v1.RecordRef `protobuf:"bytes,1,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	// Verification provider to use
	Provider *VerifyRequestProvider `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// When true, use cached verification result from server.
	// When false, verification is performed locally.
	FromServer    bool `protobuf:"varint,3,opt,name=from_server,json=fromServer,proto3" json:"from_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyRequest) GetRecordRef() *v1.RecordRef {
	if x != nil {
		return x.RecordRef
	}
	return nil
}

func (x *VerifyRequest) GetProvider() *VerifyRequestProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *VerifyRequest) GetFromServer() bool {
	if x != nil {
		return x.FromServer
	}
	return false
}

type VerifyRequestProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*VerifyRequestProvider_Key
	//	*VerifyRequestProvider_Oidc
	//	*VerifyRequestProvider_Any
	Request       isVerifyRequestProvider_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequestProvider) Reset() {
	*x = VerifyRequestProvider{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequestProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequestProvider) ProtoMessage() {}

func (x *VerifyRequestProvider) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequestProvider.ProtoReflect.Descriptor instead.
func (*VerifyRequestProvider) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyRequestProvider) GetRequest() isVerifyRequestProvider_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *VerifyRequestProvider) GetKey() *VerifyWithKey {
	if x != nil {
		if x, ok := x.Request.(*VerifyRequestProvider_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *VerifyRequestProvider) GetOidc() *VerifyWithOIDC {
	if x != nil {
		if x, ok := x.Request.(*VerifyRequestProvider_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

func (x *VerifyRequestProvider) GetAny() *VerifyWithAny {
	if x != nil {
		if x, ok := x.Request.(*VerifyRequestProvider_Any); ok {
			return x.Any
		}
	}
	return nil
}

type isVerifyRequestProvider_Request interface {
	isVerifyRequestProvider_Request()
}

type VerifyRequestProvider_Key struct {
	// Verify with PEM-encoded public key
	Key *VerifyWithKey `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

type VerifyRequestProvider_Oidc struct {
	// Verify with OIDC provider
	Oidc *VerifyWithOIDC `protobuf:"bytes,2,opt,name=oidc,proto3,oneof"`
}

type VerifyRequestProvider_Any struct {
	// Verify implicitly without providing any key or OIDC information.
	// This will attempt to verify any signature found on the record.
	// This is useful for verifying records that have been signed and have signatures attached,
	// without needing to verify against a specific key or OIDC identity.
	Any *VerifyWithAny `protobuf:"bytes,3,opt,name=any,proto3,oneof"`
}

func (*VerifyRequestProvider_Key) isVerifyRequestProvider_Request() {}

func (*VerifyRequestProvider_Oidc) isVerifyRequestProvider_Request() {}

func (*VerifyRequestProvider_Any) isVerifyRequestProvider_Request() {}

type VerifyWithKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key to verify against.
	// Accepts either:
	// - PEM-encoded public key content (inline)
	// - Reference to a public key:
	//   - File path: "/path/to/cosign.pub" or "./cosign.pub"
	//   - HTTP(S) URL: "https://example.com/cosign.pub"
	//   - Environment variable: "env://COSIGN_PUBLIC_KEY"
	//   - AWS KMS: "awskms://[ENDPOINT]/[ID/ALIAS/ARN]"
	//   - GCP KMS: "gcpkms://projects/[PROJECT]/locations/[LOC]/keyRings/[RING]/cryptoKeys/[KEY]"
	//   - Azure Key Vault: "azurekms://[VAULT_NAME][VAULT_URI]/[KEY]"
	//   - Hashicorp Vault: "hashivault://[KEY]"
	//   - Kubernetes secret: "k8s://[NAMESPACE]/[SECRET_NAME]"
	//   - PKCS11 token: "pkcs11:token=...;slot-id=...;object=..."
	//   - GitLab: "gitlab://[PROJECT]"
	PublicKey     string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWithKey) Reset() {
	*x = VerifyWithKey{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWithKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWithKey) ProtoMessage() {}

func (x *VerifyWithKey) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWithKey.ProtoReflect.Descriptor instead.
func (*VerifyWithKey) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyWithKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type VerifyWithOIDC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OIDC issuer URL.
	// Accepts exact match or regular expression (e.g., "https://github.com/login/oauth")
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// OIDC subject/identity.
	// Accepts exact match or regular expression (e.g., "user@example.com")
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Verification options for OIDC
	Options       *VerifyOptionsOIDC `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWithOIDC) Reset() {
	*x = VerifyWithOIDC{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWithOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWithOIDC) ProtoMessage() {}

func (x *VerifyWithOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWithOIDC.ProtoReflect.Descriptor instead.
func (*VerifyWithOIDC) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyWithOIDC) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *VerifyWithOIDC) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *VerifyWithOIDC) GetOptions() *VerifyOptionsOIDC {
	if x != nil {
		return x.Options
	}
	return nil
}

type VerifyWithAny struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Verification options for OIDC.
	// This is used to verify only OIDC signatures on the record.
	// For key-based signatures, this field is ignored.
	OidcOptions   *VerifyOptionsOIDC `protobuf:"bytes,1,opt,name=oidc_options,json=oidcOptions,proto3,oneof" json:"oidc_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWithAny) Reset() {
	*x = VerifyWithAny{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWithAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWithAny) ProtoMessage() {}

func (x *VerifyWithAny) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWithAny.ProtoReflect.Descriptor instead.
func (*VerifyWithAny) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyWithAny) GetOidcOptions() *VerifyOptionsOIDC {
	if x != nil {
		return x.OidcOptions
	}
	return nil
}

type VerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The verify process result
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// List of all signers that signed the record.
	// Each entry represents one valid signature on the record.
	Signers []*SignerInfo `protobuf:"bytes,2,rep,name=signers,proto3" json:"signers,omitempty"`
	// Optional error message if verification failed
	ErrorMessage  *string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyResponse) GetSigners() []*SignerInfo {
	if x != nil {
		return x.Signers
	}
	return nil
}

func (x *VerifyResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// Structured information about who signed the record
type SignerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SignerInfo_Key
	//	*SignerInfo_Oidc
	Type          isSignerInfo_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerInfo) Reset() {
	*x = SignerInfo{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerInfo) ProtoMessage() {}

func (x *SignerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerInfo.ProtoReflect.Descriptor instead.
func (*SignerInfo) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{13}
}

func (x *SignerInfo) GetType() isSignerInfo_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SignerInfo) GetKey() *SignerInfoKey {
	if x != nil {
		if x, ok := x.Type.(*SignerInfo_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *SignerInfo) GetOidc() *SignerInfoOIDC {
	if x != nil {
		if x, ok := x.Type.(*SignerInfo_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

type isSignerInfo_Type interface {
	isSignerInfo_Type()
}

type SignerInfo_Key struct {
	// Key-based signer information
	Key *SignerInfoKey `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

type SignerInfo_Oidc struct {
	// OIDC-based signer information
	Oidc *SignerInfoOIDC `protobuf:"bytes,2,opt,name=oidc,proto3,oneof"`
}

func (*SignerInfo_Key) isSignerInfo_Type() {}

func (*SignerInfo_Oidc) isSignerInfo_Type() {}

// Information about a key-based signer
type SignerInfoKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key used for verification (PEM-encoded)
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Key algorithm (e.g., "ECDSA-P256", "Ed25519", "RSA")
	Algorithm     string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignerInfoKey) Reset() {
	*x = SignerInfoKey{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerInfoKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerInfoKey) ProtoMessage() {}

func (x *SignerInfoKey) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerInfoKey.ProtoReflect.Descriptor instead.
func (*SignerInfoKey) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{14}
}

func (x *SignerInfoKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SignerInfoKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// Information about an OIDC-based signer
type SignerInfoOIDC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OIDC issuer URL (e.g., "https://github.com/login/oauth")
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// OIDC subject/identity (e.g., "user@example.com")
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// X.509 certificate issuer (e.g., "CN=sigstore-intermediate,O=sigstore.dev")
	CertificateIssuer string `protobuf:"bytes,3,opt,name=certificate_issuer,json=certificateIssuer,proto3" json:"certificate_issuer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignerInfoOIDC) Reset() {
	*x = SignerInfoOIDC{}
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerInfoOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerInfoOIDC) ProtoMessage() {}

func (x *SignerInfoOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerInfoOIDC.ProtoReflect.Descriptor instead.
func (*SignerInfoOIDC) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP(), []int{15}
}

func (x *SignerInfoOIDC) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *SignerInfoOIDC) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SignerInfoOIDC) GetCertificateIssuer() string {
	if x != nil {
		return x.CertificateIssuer
	}
	return ""
}

var File_agntcy_dir_sign_v1_sign_service_proto protoreflect.FileDescriptor

var file_agntcy_dir_sign_v1_sign_service_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x73, 0x69, 0x67,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e,
	0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x61, 0x67, 0x6e,
	0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x61, 0x67,
	0x6e, 0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8f, 0x02, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x4f, 0x49, 0x44, 0x43, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x63, 0x69, 0x6f, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x75, 0x6c, 0x63, 0x69, 0x6f,
	0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6b, 0x6f, 0x72, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6b, 0x6f, 0x72, 0x55, 0x72, 0x6c,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x69, 0x64, 0x63, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x6f, 0x69, 0x64, 0x63, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x55, 0x72,
	0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x69, 0x64, 0x63, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x69, 0x64, 0x63, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x69, 0x64, 0x63, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x69, 0x64, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x74, 0x6c,
	0x6f, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x54, 0x6c,
	0x6f, 0x67, 0x22, 0xc4, 0x01, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x49, 0x44, 0x43, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x75, 0x66, 0x5f,
	0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x75, 0x66, 0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x2a,
	0x0a, 0x11, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x65, 0x64, 0x52, 0x6f, 0x6f, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x6c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x54, 0x6c, 0x6f, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x73, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x54, 0x73, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x53, 0x63, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x0b, 0x53, 0x69,
	0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x66, 0x52, 0x09, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x66, 0x12, 0x43, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x67, 0x6e, 0x74,
	0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x8d, 0x01, 0x0a,
	0x13, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73,
	0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4b,
	0x65, 0x79, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x04, 0x6f, 0x69, 0x64,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79,
	0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x49, 0x44, 0x43, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x64,
	0x63, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x93, 0x01, 0x0a,
	0x0b, 0x53, 0x69, 0x67, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01, 0x12, 0x25,
	0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x22, 0x79, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x49,
	0x44, 0x43, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x42, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f,
	0x49, 0x44, 0x43, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4b, 0x0a,
	0x0c, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x0d, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0a,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x66, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x66, 0x12, 0x45, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61,
	0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x22, 0xca, 0x01, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x67, 0x6e, 0x74,
	0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73,
	0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x57, 0x69, 0x74,
	0x68, 0x4f, 0x49, 0x44, 0x43, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x12, 0x35, 0x0a,
	0x03, 0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x67, 0x6e,
	0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x57, 0x69, 0x74, 0x68, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52,
	0x03, 0x61, 0x6e, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2e, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22,
	0x94, 0x01, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x49,
	0x44, 0x43, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x44, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64,
	0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x49, 0x44, 0x43, 0x48, 0x00, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x6f, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x57, 0x69, 0x74, 0x68, 0x41, 0x6e, 0x79, 0x12, 0x4d, 0x0a, 0x0c, 0x6f, 0x69, 0x64, 0x63, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x4f, 0x49, 0x44, 0x43, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x69, 0x64, 0x63, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6f, 0x69, 0x64, 0x63, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64,
	0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x28,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e,
	0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x38, 0x0a, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x49,
	0x44, 0x43, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x4c, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x22, 0x71, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x49,
	0x44, 0x43, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x32, 0xa9, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1f, 0x2e, 0x61, 0x67,
	0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61,
	0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x21, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63,
	0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x67,
	0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0xb8, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64,
	0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x10, 0x53, 0x69, 0x67, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x6e, 0x74, 0x63,
	0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x41, 0x44, 0x53, 0xaa, 0x02, 0x12, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79,
	0x2e, 0x44, 0x69, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x12, 0x41,
	0x67, 0x6e, 0x74, 0x63, 0x79, 0x5c, 0x44, 0x69, 0x72, 0x5c, 0x53, 0x69, 0x67, 0x6e, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x1e, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x5c, 0x44, 0x69, 0x72, 0x5c, 0x53,
	0x69, 0x67, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x15, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x3a, 0x3a, 0x44, 0x69, 0x72,
	0x3a, 0x3a, 0x53, 0x69, 0x67, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_agntcy_dir_sign_v1_sign_service_proto_rawDescOnce sync.Once
	file_agntcy_dir_sign_v1_sign_service_proto_rawDescData []byte
)

func file_agntcy_dir_sign_v1_sign_service_proto_rawDescGZIP() []byte {
	file_agntcy_dir_sign_v1_sign_service_proto_rawDescOnce.Do(func() {
		file_agntcy_dir_sign_v1_sign_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_dir_sign_v1_sign_service_proto_rawDesc), len(file_agntcy_dir_sign_v1_sign_service_proto_rawDesc)))
	})
	return file_agntcy_dir_sign_v1_sign_service_proto_rawDescData
}

var file_agntcy_dir_sign_v1_sign_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_agntcy_dir_sign_v1_sign_service_proto_goTypes = []any{
	(*SignOptionsOIDC)(nil),       // 0: agntcy.dir.sign.v1.SignOptionsOIDC
	(*VerifyOptionsOIDC)(nil),     // 1: agntcy.dir.sign.v1.VerifyOptionsOIDC
	(*SignRequest)(nil),           // 2: agntcy.dir.sign.v1.SignRequest
	(*SignRequestProvider)(nil),   // 3: agntcy.dir.sign.v1.SignRequestProvider
	(*SignWithKey)(nil),           // 4: agntcy.dir.sign.v1.SignWithKey
	(*SignWithOIDC)(nil),          // 5: agntcy.dir.sign.v1.SignWithOIDC
	(*SignResponse)(nil),          // 6: agntcy.dir.sign.v1.SignResponse
	(*VerifyRequest)(nil),         // 7: agntcy.dir.sign.v1.VerifyRequest
	(*VerifyRequestProvider)(nil), // 8: agntcy.dir.sign.v1.VerifyRequestProvider
	(*VerifyWithKey)(nil),         // 9: agntcy.dir.sign.v1.VerifyWithKey
	(*VerifyWithOIDC)(nil),        // 10: agntcy.dir.sign.v1.VerifyWithOIDC
	(*VerifyWithAny)(nil),         // 11: agntcy.dir.sign.v1.VerifyWithAny
	(*VerifyResponse)(nil),        // 12: agntcy.dir.sign.v1.VerifyResponse
	(*SignerInfo)(nil),            // 13: agntcy.dir.sign.v1.SignerInfo
	(*SignerInfoKey)(nil),         // 14: agntcy.dir.sign.v1.SignerInfoKey
	(*SignerInfoOIDC)(nil),        // 15: agntcy.dir.sign.v1.SignerInfoOIDC
	(*v1.RecordRef)(nil),          // 16: agntcy.dir.core.v1.RecordRef
	(*Signature)(nil),             // 17: agntcy.dir.sign.v1.Signature
}
var file_agntcy_dir_sign_v1_sign_service_proto_depIdxs = []int32{
	16, // 0: agntcy.dir.sign.v1.SignRequest.record_ref:type_name -> agntcy.dir.core.v1.RecordRef
	3,  // 1: agntcy.dir.sign.v1.SignRequest.provider:type_name -> agntcy.dir.sign.v1.SignRequestProvider
	4,  // 2: agntcy.dir.sign.v1.SignRequestProvider.key:type_name -> agntcy.dir.sign.v1.SignWithKey
	5,  // 3: agntcy.dir.sign.v1.SignRequestProvider.oidc:type_name -> agntcy.dir.sign.v1.SignWithOIDC
	0,  // 4: agntcy.dir.sign.v1.SignWithOIDC.options:type_name -> agntcy.dir.sign.v1.SignOptionsOIDC
	17, // 5: agntcy.dir.sign.v1.SignResponse.signature:type_name -> agntcy.dir.sign.v1.Signature
	16, // 6: agntcy.dir.sign.v1.VerifyRequest.record_ref:type_name -> agntcy.dir.core.v1.RecordRef
	8,  // 7: agntcy.dir.sign.v1.VerifyRequest.provider:type_name -> agntcy.dir.sign.v1.VerifyRequestProvider
	9,  // 8: agntcy.dir.sign.v1.VerifyRequestProvider.key:type_name -> agntcy.dir.sign.v1.VerifyWithKey
	10, // 9: agntcy.dir.sign.v1.VerifyRequestProvider.oidc:type_name -> agntcy.dir.sign.v1.VerifyWithOIDC
	11, // 10: agntcy.dir.sign.v1.VerifyRequestProvider.any:type_name -> agntcy.dir.sign.v1.VerifyWithAny
	1,  // 11: agntcy.dir.sign.v1.VerifyWithOIDC.options:type_name -> agntcy.dir.sign.v1.VerifyOptionsOIDC
	1,  // 12: agntcy.dir.sign.v1.VerifyWithAny.oidc_options:type_name -> agntcy.dir.sign.v1.VerifyOptionsOIDC
	13, // 13: agntcy.dir.sign.v1.VerifyResponse.signers:type_name -> agntcy.dir.sign.v1.SignerInfo
	14, // 14: agntcy.dir.sign.v1.SignerInfo.key:type_name -> agntcy.dir.sign.v1.SignerInfoKey
	15, // 15: agntcy.dir.sign.v1.SignerInfo.oidc:type_name -> agntcy.dir.sign.v1.SignerInfoOIDC
	2,  // 16: agntcy.dir.sign.v1.SignService.Sign:input_type -> agntcy.dir.sign.v1.SignRequest
	7,  // 17: agntcy.dir.sign.v1.SignService.Verify:input_type -> agntcy.dir.sign.v1.VerifyRequest
	6,  // 18: agntcy.dir.sign.v1.SignService.Sign:output_type -> agntcy.dir.sign.v1.SignResponse
	12, // 19: agntcy.dir.sign.v1.SignService.Verify:output_type -> agntcy.dir.sign.v1.VerifyResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_agntcy_dir_sign_v1_sign_service_proto_init() }
func file_agntcy_dir_sign_v1_sign_service_proto_init() {
	if File_agntcy_dir_sign_v1_sign_service_proto != nil {
		return
	}
	file_agntcy_dir_sign_v1_signature_proto_init()
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[3].OneofWrappers = []any{
		(*SignRequestProvider_Key)(nil),
		(*SignRequestProvider_Oidc)(nil),
	}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[8].OneofWrappers = []any{
		(*VerifyRequestProvider_Key)(nil),
		(*VerifyRequestProvider_Oidc)(nil),
		(*VerifyRequestProvider_Any)(nil),
	}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_agntcy_dir_sign_v1_sign_service_proto_msgTypes[13].OneofWrappers = []any{
		(*SignerInfo_Key)(nil),
		(*SignerInfo_Oidc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_dir_sign_v1_sign_service_proto_rawDesc), len(file_agntcy_dir_sign_v1_sign_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agntcy_dir_sign_v1_sign_service_proto_goTypes,
		DependencyIndexes: file_agntcy_dir_sign_v1_sign_service_proto_depIdxs,
		MessageInfos:      file_agntcy_dir_sign_v1_sign_service_proto_msgTypes,
	}.Build()
	File_agntcy_dir_sign_v1_sign_service_proto = out.File
	file_agntcy_dir_sign_v1_sign_service_proto_goTypes = nil
	file_agntcy_dir_sign_v1_sign_service_proto_depIdxs = nil
}
